/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(c){function h(){var b={};this.name?b[this.name]=this.value:b[this.id]=this.checked;chrome.storage.local.set(b)}function Ia(){for(var b=[],d=0;d<u.length;d++)u[d].checked&&b.push(u[d].id);chrome.storage.local.set({controls:b});if(d=c.querySelector("#firefox-bug"))d.classList[-1!==b.indexOf("volume-booster")?"remove":"add"]("hidden")}function sa(){for(var b=c.querySelectorAll('#customcolors input[type="color"'),d={},e=0;e<b.length;e++)d[b[e].name]=b[e].value;chrome.storage.local.set({customcolors:d})}
function ta(){fetch(`_locales/${n}/messages.json`).then(function(b){return b.json()}).then(function(b){C=b.locale_dir.message;c.documentElement.lang=n.replace("_","-");c.body.dir=C;for(var d=x.length-1;0<=d;d--)x[d].textContent=b[x[d].dataset.text].message;for(d=r.length-1;0<=d;d--)r[d].dataset.tooltip=b[r[d].dataset.message].message;c.querySelector("#customcssrules").setAttribute("placeholder",b.custom_theme_instructions.message);c.querySelector("#customscript").setAttribute("placeholder",b.custom_script_instructions.message);
chrome.storage.local.set({localecode:n,localedir:C})})}function O(){var b=c.querySelector("#channels");b.textContent="";l.forEach(function(d){var e=c.createElement("bdi"),q=c.createElement("span"),t=c.createElementNS("http://www.w3.org/2000/svg","svg"),p=c.createElementNS("http://www.w3.org/2000/svg","path");q.textContent=d;e.appendChild(q);t.setAttributeNS(null,"version","1.1");t.setAttributeNS(null,"viewBox","0 0 24 24");p.setAttributeNS(null,"d","M0 0h24v24H0V0z");p.setAttributeNS(null,"fill",
"none");t.appendChild(p);p=c.createElementNS("http://www.w3.org/2000/svg","path");p.setAttributeNS(null,"d","M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm5 13.59L15.59 17 12 13.41 8.41 17 7 15.59 10.59 12 7 8.41 8.41 7 12 10.59 15.59 7 17 8.41 13.41 12 17 15.59z");t.appendChild(p);t.addEventListener("click",Ja);e.appendChild(t);b.appendChild(e)})}function Ja(){l.splice(l.indexOf(this.parentNode.textContent),1);chrome.storage.local.set({whitelist:l.toString()});O()}function ia(b){c.body.classList.add("overflow-hidden");
D.style.display="block";b.style.display="block";b.scrollTop=0;D.classList.add("in");setTimeout(function(){c.body.classList.add("modal-open")},50)}function ua(b){c.body.classList.remove("modal-open");setTimeout(function(){b.style.display="none";D.classList.add("fade");D.classList.remove("in");setTimeout(function(){D.style.display="none";c.body.classList.remove("overflow-hidden")},300)},300)}var n=chrome.i18n.getMessage("locale_code"),C=chrome.i18n.getMessage("locale_dir"),x=c.querySelectorAll(".i18n"),
D=c.querySelector("#modal-backdrop"),r=c.querySelectorAll(".player-control .info"),u,l,y={blur:0,brightness:100,contrast:100,grayscale:0,huerotate:0,invert:0,saturate:100,sepia:0,applyvideofilters:!1,backgroundcolor:"#000000",backgroundopacity:85,blackbars:!1,blockads:!0,blockadsexceptforsubs:!1,blockautoplay:!0,blockhfrformats:!1,blockwebmformats:!1,boostvolume:!1,cinemamode:!1,cinemamodewideplayer:!0,controlbar:{active:!0,autohide:!1,centered:!0,position:"absolute"},controls:"loop reverse-playlist volume-booster whitelist not-interested cards-end-screens cinema-mode size pop-up-player speed video-filters screenshot keyboard-shortcuts options".split(" "),
controlsvisible:!1,controlspeed:!0,controlspeedmousebutton:!1,controlvolume:!1,controlvolumemousebutton:!1,convertshorts:!1,customcolors:{"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"},customcssrules:"",customscript:"",customtheme:!1,darktheme:!1,date:0,defaultvolume:!1,disableautoplay:!1,executescript:!1,expanddescription:!1,filter:"none",hidecardsendscreens:!1,
hidechat:!1,hidecomments:!1,hiderelated:!1,hideshorts:!1,ignoreplaylists:!0,ignorepopupplayer:!0,localecode:n,localedir:C,message:!1,miniplayer:!0,miniplayerposition:"_top-left",miniplayersize:"_400x225",newestcomments:!1,overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,popuplayersize:"640x360",qualityembeds:"medium",qualityembedsfullscreen:"hd1080",qualityplaylists:"hd720",qualityplaylistsfullscreen:"hd1080",qualityvideos:"hd720",qualityvideosfullscreen:"hd1080",reload:!1,reversemousewheeldirection:!1,
selectquality:!1,selectqualityfullscreenoff:!1,selectqualityfullscreenon:!1,speed:1,speedvariation:.1,stopvideos:!1,theatermode:!1,theme:"default-dark",themevariant:"youtube-deep-dark.css",update:0,volume:50,volumemultiplier:3,volumevariation:5,whitelist:"",wideplayer:!1,wideplayerviewport:!1};chrome.storage.local.get(y,function(b){if(n===b.localecode){c.documentElement.lang=n.replace("_","-");c.body.dir=C;for(var d=x.length-1;0<=d;d--)x[d].textContent=chrome.i18n.getMessage(x[d].dataset.text);for(d=
r.length-1;0<=d;d--)r[d].dataset.tooltip=chrome.i18n.getMessage(r[d].dataset.message);c.querySelector("#customcssrules").setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));c.querySelector("#customscript").setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"))}else n=b.localecode,ta();c.querySelectorAll("nav a").forEach(function(a){a.addEventListener("focus",function(){this.parentNode.classList.add("focus")});a.addEventListener("blur",function(){this.parentNode.classList.remove("focus")})});
var e=c.querySelector("nav .donate a"),q=c.querySelector("#donate-modal"),t=q.querySelector(".close-modal");e.addEventListener("click",function(a){a.preventDefault();a=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(n)?"USD":"EUR";q.querySelector(".donate-buttons").dataset.currencyCode=a;ia(q)});q.querySelectorAll(".donate-buttons button").forEach(function(a){a.addEventListener("click",function(){var g=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(n)?
"USD":"EUR";g=e.dataset.paypal.replace(/AMOUNT/,this.dataset.amount).replace(/CURRENCY_CODE/,g);chrome.tabs.create({url:g,active:!0})})});t.addEventListener("click",function(){ua(q)});d=c.querySelector("#locale");d.value=n;d.addEventListener("change",function(){n=this.value;ta()});d.addEventListener("focus",function(){this.parentNode.classList.add("focus")});d.addEventListener("blur",function(){this.parentNode.classList.remove("focus")});"#boostvolume #blackbars #cinemamode #cinemamodewideplayer #reversemousewheeldirection #hidecardsendscreens #hidecomments #hidechat #hiderelated #hideshorts #convertshorts #wideplayer #wideplayerviewport #applyvideofilters #blockhfrformats #blockwebmformats #expanddescription #newestcomments #executescript".split(" ").forEach(function(a){a=
c.querySelector(a);a.checked=b[a.id];a.addEventListener("click",h)});c.querySelector("#keyboard-shortcuts-btn").addEventListener("click",function(){chrome.runtime.sendMessage({request:"configure-keyboard-shortcuts"})});u=c.querySelectorAll('.player-control input[type="checkbox"]');for(d=0;d<u.length;d++)u[d].checked=-1<b.controls.indexOf(u[d].id)?!0:!1,u[d].addEventListener("click",Ia);var p=c.querySelector("#firefox-bug");if(p)try{browser.runtime.getBrowserInfo().then(a=>{if(91<=parseInt(a.version))p.parentNode.removeChild(p);
else p.classList[-1!==b.controls.indexOf("volume-booster")?"remove":"add"]("hidden")})}catch(a){}r=c.querySelectorAll(".player-control .info");for(d=r.length-1;0<=d;d--)r[d].addEventListener("click",function(a){a.preventDefault()});var k=c.querySelectorAll('input[name="controlbaractive"]'),E=c.querySelector("#controlsvisible"),F=c.querySelector("#controlbarposition"),va=c.querySelector("#control-bar-centering"),G=c.querySelector("#controlbarcentered"),wa=c.querySelector("#control-bar-visibility"),
H=c.querySelector("#controlbarautohide");for(d=0;d<k.length;d++)k[d].value===String(b.controlbar.active)&&(k[d].checked=!0),k[d].addEventListener("click",function(){"false"===this.value?(b.controlbar.active=!1,E.disabled=!1,F.disabled=!0,G.disabled=!0,H.disabled=!0):(b.controlbar.active=!0,E.disabled=!0,F.disabled=!1,G.disabled=!1,H.disabled=!1);chrome.storage.local.set({controlbar:b.controlbar})});E.checked=b.controlsvisible;E.disabled=b.controlbar.active;E.addEventListener("click",h);F.value=b.controlbar.position;
F.disabled=!b.controlbar.active;F.addEventListener("change",function(){va.classList["absolute"===this.value?"remove":"add"]("hidden");wa.classList["fixed"===this.value?"remove":"add"]("hidden");b.controlbar.position=this.value;chrome.storage.local.set({controlbar:b.controlbar})});va.classList["absolute"===b.controlbar.position?"remove":"add"]("hidden");G.checked=b.controlbar.centered;G.disabled=!b.controlbar.active;G.addEventListener("click",function(a){b.controlbar.centered=this.checked;chrome.storage.local.set({controlbar:b.controlbar})});
wa.classList["fixed"===b.controlbar.position?"remove":"add"]("hidden");H.checked=b.controlbar.autohide;H.disabled=!b.controlbar.active;H.addEventListener("click",function(a){b.controlbar.autohide=this.checked;chrome.storage.local.set({controlbar:b.controlbar})});d=c.querySelector("#backgroundcolor");k=c.querySelector("#backgroundopacity");var Ka=c.querySelector("#opacity"),La=c.querySelector("#cinemamode-background"),ja=function(){var a=b.backgroundcolor.replace("#",""),g=parseInt(a.substring(0,2),
16),f=parseInt(a.substring(2,4),16);a=parseInt(a.substring(4,6),16);Ka.textContent=b.backgroundopacity+"%";La.style.backgroundColor=`rgba(${g}, ${f}, ${a}, ${b.backgroundopacity/100})`};d.value=b.backgroundcolor;d.addEventListener("input",function(){b.backgroundcolor=this.value;ja();chrome.storage.local.set({backgroundcolor:this.value})});d.addEventListener("change",h);k.value=b.backgroundopacity;k.addEventListener("input",function(){b.backgroundopacity=Number(this.value);ja();chrome.storage.local.set({backgroundopacity:b.backgroundopacity})});
ja();var I=c.querySelector("#playback-speed"),J=c.querySelector("#custom-playback-speed");d=c.querySelector("#overridespeeds");var P=c.querySelector("#speedvariation");k=c.querySelector("#defaultvolume");var Q=c.querySelector("#volume"),xa=c.querySelector("#volume-preview"),z=c.querySelector("#volumemultiplier"),R=c.querySelector("#controlspeed"),S=c.querySelector("#controlspeedmousebutton"),ya=c.querySelector("#controlvolume"),T=c.querySelector("#controlvolumemousebutton"),U=c.querySelector("#volumevariation"),
za=c.querySelector("#miniplayer"),V=c.querySelector("#miniplayersize"),W=c.querySelector("#miniplayerposition");I.value=b.overridespeeds?1:b.speed;I.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});J.value=b.overridespeeds?b.speed:1;J.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});b.overridespeeds&&(I.classList.add("hidden"),J.classList.remove("hidden"));d.checked=b.overridespeeds;d.addEventListener("click",
function(){P.disabled=!this.checked;var a=c.querySelector("#playback-speed-label");a.classList.add("animated","blink");setTimeout(function(){a.classList.remove("animated","blink")},2400);I.classList.toggle("hidden");J.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?J.value:I.value)})});P.value=b.speedvariation;P.disabled=!b.overridespeeds;P.addEventListener("change",function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});
R.checked=b.controlspeed;R.addEventListener("click",function(){S.disabled=!this.checked;chrome.storage.local.set({controlspeed:this.checked})});S.checked=b.controlspeedmousebutton;S.disabled=!b.controlspeed;S.addEventListener("click",h);k.checked=b.defaultvolume;k.addEventListener("click",function(){Q.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});Q.value=b.volume;Q.disabled=!b.defaultvolume;Q.addEventListener("input",function(){b.volume=Number(this.value);xa.textContent=
b.volume;chrome.storage.local.set({volume:b.volume})});xa.textContent=b.volume;z.value=b.volumemultiplier;z.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});ya.checked=b.controlvolume;ya.addEventListener("click",function(){T.disabled=!this.checked;U.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});T.checked=b.controlvolumemousebutton;T.disabled=!b.controlvolume;T.addEventListener("click",h);U.value=b.volumevariation;
U.disabled=!b.controlvolume;U.addEventListener("change",function(){chrome.storage.local.set({volumevariation:Number(this.value)})});z.value=b.volumemultiplier;z.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});za.checked=b.miniplayer;za.addEventListener("click",function(){V.disabled=!this.checked;W.disabled=!this.checked;chrome.storage.local.set({miniplayer:this.checked})});V.value=b.miniplayersize;V.disabled=!b.miniplayer;V.addEventListener("change",
h);W.value=b.miniplayerposition;W.disabled=!b.miniplayer;W.addEventListener("change",h);d=c.querySelector("#blockads");var X=c.querySelector("#blockadsexceptforsubs"),Aa=c.querySelector("#whitelist-section"),ka=c.querySelector("#channel"),Ba=c.querySelector("#whitelist-channel-btn");(d.checked=b.blockads)&&Aa.classList.remove("hidden");d.addEventListener("click",function(){X.disabled=!this.checked;Aa.classList.toggle("hidden");chrome.storage.local.set({blockads:this.checked})});X.checked=b.blockadsexceptforsubs;
X.disabled=!b.blockads;X.addEventListener("click",h);ka.addEventListener("keydown",function(a){13===a.keyCode&&Ba.click()});l=""!==b.whitelist?b.whitelist.split(","):[];0<l.length&&O();Ba.addEventListener("click",function(){var a=ka.value.replace(/,/g,"").trim();if(""!==a&&0>l.indexOf(a)){l.push(a);try{l.sort(function(g,f){return g.localeCompare(f)})}catch(g){l.sort()}chrome.storage.local.set({whitelist:l.toString()});O()}ka.value=""});d=c.querySelector("#blockautoplay");var Y=c.querySelector("#pauseforegroundtab"),
Z=c.querySelector("#ignoreplaylists"),aa=c.querySelector("#stopvideos");d.checked=b.blockautoplay;d.addEventListener("click",function(){Y.disabled=!this.checked;Z.disabled=!this.checked;aa.disabled=!this.checked;chrome.storage.local.set({blockautoplay:this.checked})});Y.checked=b.pauseforegroundtab;Y.disabled=!b.blockautoplay;Y.addEventListener("click",h);Z.checked=b.ignoreplaylists;Z.disabled=!b.blockautoplay;Z.addEventListener("click",h);aa.checked=b.stopvideos;aa.disabled=!b.blockautoplay;aa.addEventListener("click",
h);d=c.querySelector("#pausevideos");var ba=c.querySelector("#ignorepopupplayer");d.checked=b.pausevideos;d.addEventListener("click",function(){ba.disabled=!this.checked;chrome.storage.local.set({pausevideos:this.checked})});ba.checked=b.ignorepopupplayer;ba.disabled=!b.pausevideos;ba.addEventListener("click",h);d=c.querySelector("#disableautoplay");var Ca=c.querySelector(".autoplay-toggle-button");d.checked=b.disableautoplay;Ca.setAttribute("aria-checked",!b.disableautoplay);d.addEventListener("click",
function(){Ca.setAttribute("aria-checked",!this.checked);chrome.storage.local.set({disableautoplay:this.checked})});var la=c.querySelector("#selectquality"),v=c.querySelector("#selectqualityfullscreenon"),K=c.querySelector("#selectqualityfullscreenoff"),ca=["#qualityvideos","#qualityplaylists","#qualityembeds"],da=["#qualityvideosfullscreen","#qualityplaylistsfullscreen","#qualityembedsfullscreen"];la.checked=b.selectquality;la.addEventListener("click",function(){ca.forEach(function(a){c.querySelector(a).disabled=
!la.checked});v.disabled=!this.checked;this.checked?(ca.forEach(function(a){c.querySelector(a).disabled=!1}),v.disabled=!1,v.checked&&(da.forEach(function(a){c.querySelector(a).disabled=!1}),K.disabled=!1)):(ca.forEach(function(a){c.querySelector(a).disabled=!0}),v.disabled=!0,da.forEach(function(a){c.querySelector(a).disabled=!0}),K.disabled=!0);chrome.storage.local.set({selectquality:this.checked})});ca.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectquality;a.addEventListener("change",
h)});v.checked=b.selectqualityfullscreenon;v.addEventListener("click",function(){da.forEach(function(a){c.querySelector(a).disabled=!v.checked});K.disabled=!this.checked;chrome.storage.local.set({selectqualityfullscreenon:this.checked})});da.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectqualityfullscreenon;a.addEventListener("change",h)});K.checked=b.selectqualityfullscreenoff;K.addEventListener("click",h);d=c.querySelector("#popuplayersize");d.value=b.popuplayersize;
d.addEventListener("change",h);d=c.querySelector("#theatermode");d.checked=b.theatermode;d.addEventListener("click",function(){chrome.cookies.set({url:"https://www.youtube.com/watch",name:"wide",value:this.checked?"1":"0",domain:".youtube.com",path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});chrome.storage.local.set({theatermode:this.checked})});var ea=c.querySelector("#darktheme"),w=c.querySelectorAll('input[name="theme"]'),L=c.querySelector("#themevariant"),ma=c.querySelector("#customcolors"),
na=c.querySelector("#reset-custom-colors");k=c.querySelector("#customtheme");var M=c.querySelector("#customcssrules");z=c.querySelector("#customcssrules-btn");var fa=c.querySelector("#customcssrules-checkmark");d=w.length-1;ea.checked=b.darktheme;for(ea.addEventListener("click",function(){w.forEach(function(a){a.disabled=!ea.checked});L.disabled=this.checked?"youtube-deep-dark"===c.querySelector('input[name="theme"]:checked').value?!1:!0:!0;c.querySelectorAll('#customcolors input[type="color"]').forEach(function(a){a.disabled=
!ea.checked});na.disabled=!this.checked;chrome.storage.local.set({darktheme:this.checked})});0<=d;d--)w[d].value===b.theme&&(w[d].checked=!0),w[d].disabled=!b.darktheme,w[d].addEventListener("click",h),w[d].addEventListener("click",function(){L.disabled="youtube-deep-dark"===this.value?!1:!0;ma.classList["youtube-deep-dark-custom"===this.value?"remove":"add"]("hidden")});L.value=b.themevariant;L.disabled=b.darktheme?"youtube-deep-dark"===b.theme?!1:!0:!0;L.addEventListener("change",h);ma.classList["youtube-deep-dark-custom"===
b.theme?"remove":"add"]("hidden");var A=ma.querySelectorAll('input[type="color"');R=b.customcolors;for(d=A.length-1;0<=d;d--)A[d].disabled=!b.darktheme,A[d].value=R[A[d].name],A[d].addEventListener("change",sa);na.disabled=!b.darktheme;na.addEventListener("click",function(){var a=y.customcolors;A.forEach(function(g){g.value=a[g.name]});sa()});k.checked=b.customtheme;k.addEventListener("click",function(){M.parentNode.classList[this.checked?"remove":"add"]("hidden");chrome.storage.local.set({customtheme:this.checked})});
M.value=b.customcssrules;M.parentNode.classList[b.customtheme?"remove":"add"]("hidden");M.addEventListener("focus",function(){fa.classList.remove("show")});z.addEventListener("click",function(){fa.classList.add("show");chrome.storage.local.set({customcssrules:M.value})});fa.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){fa.classList.remove("show")},1200)});var oa=c.querySelector("#customscript");d=c.querySelector("#customscript-btn");var ha=
c.querySelector("#customscript-checkmark");oa.value=b.customscript;oa.addEventListener("focus",function(){ha.classList.remove("show")});d.addEventListener("click",function(){ha.classList.add("show");chrome.storage.local.set({customscript:oa.value})});ha.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){ha.classList.remove("show")},1200)});d=c.querySelector("#export-modal-btn");k=c.querySelector("#import-modal-btn");var m=c.querySelector("#backup-modal"),
Da=m.querySelector(".close-modal"),Ea=m.querySelector("#export-modal-content"),Fa=m.querySelector("#export-textarea"),Ga=m.querySelector("#import-modal-content"),pa=m.querySelector("#import-error"),Ha=m.querySelector("#import-textarea"),qa=m.querySelector("#import-btn"),ra=m.querySelector("#copy-to-clipboard-btn"),N=m.querySelector("#copy-to-clipboard-checkmark");d.addEventListener("click",function(){Ea.classList.remove("hidden");ra.classList.remove("hidden");N.classList.remove("hidden");ia(m);chrome.storage.local.get(null,
function(a){var g={};g.version=chrome.runtime.getManifest().version;g.settings={};Object.keys(y).forEach(function(f){g.settings[f]="undefined"===typeof a[f]?y[f]:a[f]});Fa.value=JSON.stringify(g)})});k.addEventListener("click",function(){Ga.classList.remove("hidden");qa.classList.remove("hidden");ia(m)});Da.addEventListener("click",function(){ua(m);setTimeout(function(){Ea.classList.add("hidden");Ga.classList.add("hidden");pa.classList.add("hidden");qa.classList.add("hidden");ra.classList.add("hidden");
N.classList.add("hidden");Ha.value=""},600)});ra.addEventListener("click",function(a){Fa.select();c.execCommand("copy");N.classList.add("show")});N.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){N.classList.remove("show")},1200)});qa.addEventListener("click",function(){var a=Ha.value.trim(),g={};if(""!==a){try{a=JSON.parse(a)}catch(B){pa.classList.remove("hidden");return}if("object"===typeof a.settings){if(a.version&&/2\.0\.103/.test(a.version))"default-light"===
a.settings.theme?a.settings.theme="default-dark":a.settings.darktheme=!0;else if(a.version&&/2\.0\.(9|10[0-1])/.test(a.version))try{a.settings.customcolors=y.customcolors;a.settings.customcssrules=a.settings.customtheme;a.settings.customtheme="custom"===a.settings.theme?!0:!1;"default"===a.settings.theme||"custom"===a.settings.theme?(a.settings.themevariant="youtube-deep-dark.css",a.settings.theme="default-dark"):(a.settings.themevariant=a.settings.theme,a.settings.theme="youtube-deep-dark",a.settings.darktheme=
!0);var f=[];f.push("loop");f.push("reverse-playlist");0<=a.settings.toolbarbuttons.indexOf("boost")&&f.push("volume-booster");f.push("not-interested");0<=a.settings.toolbarbuttons.indexOf("cinema")&&f.push("cinema-mode");0<=a.settings.toolbarbuttons.indexOf("resize")&&f.push("size");f.push("pop-up-player");0<=a.settings.toolbarbuttons.indexOf("slowdown")&&f.push("speed-minus");f.push("speed");0<=a.settings.toolbarbuttons.indexOf("speedup")&&f.push("speed-plus");f.push("video-filters");f.push("screenshot");
f.push("keyboard-shortcuts");0<=a.settings.toolbarbuttons.indexOf("script")&&f.push("custom-script");0<=a.settings.toolbarbuttons.indexOf("options")&&f.push("options");a.settings.controls=f;a.settings.applyvideofilters=a.settings.enablefilters;a.settings.blockads=a.settings.removeads;a.settings.blockautoplay=a.settings.autopausevideos;a.settings.customscript=a.settings.script;a.settings.hidecardsendscreens=a.settings.removeannotations;a.settings.miniplayer=a.settings.pinnedplayer;a.settings.miniplayerposition=
a.settings.pinnedplayerposition;a.settings.miniplayersize=a.settings.pinnedplayersize;a.settings.qualityembeds=a.settings.quality2;a.settings.qualityembedsfullscreen=a.settings.quality1;a.settings.qualityplaylists=a.settings.quality1;a.settings.qualityplaylistsfullscreen=a.settings.quality1;a.settings.qualityvideos=a.settings.quality1;a.settings.qualityvideosfullscreen=a.settings.quality1;a.settings.stopvideos=a.settings.disablepreloading;delete a.settings.autofocusevents;delete a.settings.autopausevideos;
delete a.settings.disablepreloading;delete a.settings.enablefilters;delete a.settings.permissions;delete a.settings.pinnedplayer;delete a.settings.pinnedplayerposition;delete a.settings.pinnedplayersize;delete a.settings.quality1;delete a.settings.quality2;delete a.settings.quality3;delete a.settings.quality4;delete a.settings.removeads;delete a.settings.removeannotations;delete a.settings.script;delete a.settings.slideeffect;delete a.settings.toolbarbackgroundcolor;delete a.settings.toolbarbordercolor;
delete a.settings.toolbarbuttons;delete a.settings.toolbarcolor;delete a.settings.toolbarcoloractive;delete a.settings.toolbaropacity;delete a.settings.toolbartooltips;delete a.settings.transparency;delete a.settings.visitor_info1_live}catch(B){}Object.keys(a.settings).forEach(function(B){typeof y[B]===typeof a.settings[B]&&(g[B]=a.settings[B])});chrome.storage.local.clear(function(){chrome.runtime.lastError&&(c.documentElement.dataset.e=1);chrome.storage.local.set(g,function(){window.scrollTo(0,
0);c.location.reload()})})}else pa.classList.remove("hidden")}});c.addEventListener("keydown",function(a){27===a.keyCode&&(Da.click(),t.click())})});chrome.storage.onChanged.addListener(function(b,d){for(var e in b)if("undefined"!==typeof b[e].newValue)if("whitelist"===e&&b[e].newValue!==l.toString())l=""!==b[e].newValue?b[e].newValue.split(","):[],O();else if("darktheme"===e&&b[e].newValue!==c.querySelector("#darktheme").checked)c.querySelector("#darktheme").click();else if("theme"===e&&b[e].newValue!==
c.querySelector('input[name="theme"]:checked').value)c.querySelector(`input[name="theme"][value="${b[e].newValue}"]`).checked=!0,c.querySelector("#themevariant").disabled="youtube-deep-dark"===b[e].newValue?!1:!0,c.querySelector("#customcolors").classList["youtube-deep-dark-custom"===b[e].newValue?"remove":"add"]("hidden");else if("customtheme"===e){d=c.querySelector("#customtheme");var q=c.querySelector("#customcssrules");d.checked!==b[e].newValue&&(d.checked=b[e].newValue,q.parentNode.classList[b[e].newValue?
"remove":"add"]("hidden"))}})})(document);